
class-list:
  - vibration_damper
  - festoon_insulators
  - traverse
  - nest
  - safety_sign+
  - bad_insulator
  - damaged_insulator
  - polymer_insulators

input: images
output: output0
size:
  width: 864
  height: 864

conf-threshold: 0.7
NMS-threshold: 0.5
